name: Try

on: push

jobs:
  linux:
    name: try on linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@master
      - name: Install
        run: yarn
      - name: Build
        run: yarn workflow
      - name: Show
        run: |
          cat dist/src/index.js
          cat dist/config/index.js

  windows:
    name: try on windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@master
      - name: Install
        run: yarn
      - name: Build
        run: yarn workflow
      - name: Show
        run: |
          type dist\src\index.js
          type dist\config\index.js
